apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-codingboss
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-codingboss
  template:
    metadata:
      labels:
        app: app-codingboss
    spec:
      containers:
      - name: app-codingboss
        imagePullPolicy: Always
        image: ${IMAGE_NAME}  # Replace with your image
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: registry-auth

---

apiVersion: v1
kind: Service
metadata:
  name: app-codingboss-service
spec:
  selector:
    app: app-codingboss
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP  # Internal service for the ingress to use